CREATE DATABASE mailman;

CREATE TABLE addressBook
(
  ID INT UNSIGNED NOT NULL  AUTO_INCREMENT, PRIMARY KEY (ID),
  firstName VARCHAR(255),
  lastName VARCHAR(255),
  eMail VARCHAR(255),
  joined TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  optOut TINYINT
);